server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: bus-service
          uri: lb://bus-service
          predicates:
            - Path=/bus/**
        - id: bookings-service
          uri: lb://bookings-service
          predicates:
            - Path=/bookings/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE